AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AwsJsSdkV3Workshop

  Backend for the AWS JS SDK v3 workshop

Globals:
  Api:
    Cors: "'*'"
  Function:
    Runtime: nodejs10.x
    Timeout: 180
    Environment:
      Variables:
        tableName: !Ref NotesTable

Resources:
  NotesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: aws-js-sdk-workshop-notes
      PrimaryKey:
        Name: noteId
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  CreateNote:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: create.main
      Policies:
        # Update to just "dynamodb:PutItem"
        - DynamoDBCrudPolicy:
            TableName: !Ref NotesTable
      Events:
        CreateNote:
          Type: Api
          Properties:
            Path: /notes
            Method: post
  GetNote:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: get.main
      Policies:
        # Update to just "dynamodb:GetItem"
        - DynamoDBReadPolicy:
            TableName: !Ref NotesTable
      Events:
        GetNote:
          Type: Api
          Properties:
            Path: /notes/{id}
            Method: get
  ListNotes:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: list.main
      Policies:
        # Update to just "dynamodb:Scan"
        - DynamoDBReadPolicy:
            TableName: !Ref NotesTable
      Events:
        ListNotes:
          Type: Api
          Properties:
            Path: /notes
            Method: get
  UpdateNote:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: update.main
      Policies:
        # Update to just "dynamodb:UpdateItem"
        - DynamoDBCrudPolicy:
            TableName: !Ref NotesTable
      Events:
        UpdateNote:
          Type: Api
          Properties:
            Path: /notes/{id}
            Method: put
  DeleteNote:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: delete.main
      Policies:
        # Update to just "dynamodb:DeleteItem"
        - DynamoDBCrudPolicy:
            TableName: !Ref NotesTable
      Events:
        DeleteNote:
          Type: Api
          Properties:
            Path: /notes/{id}
            Method: delete

Outputs:
  NotesApi:
    Description: "API Gateway endpoint URL for Notes API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"
